version: '3.7'

services:
  redis1:
    image: bitnami/redis:latest
    container_name: Redis1
    restart: always
    ports: 
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - redis-cluster
    command:  redis1-server --loglevel warning --requirepass debuggeandoideas
  redis2:
    image: bitnami/redis:latest
    container_name: Redis2
    restart: always
    ports: 
      - '6380:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - redis-cluster
    command:  Redis2-server --loglevel warning --requirepass debuggeandoideas
  redis3:
    image: bitnami/redis:latest
    container_name: Redis3
    restart: always
    ports: 
      - '6381:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - redis-cluster
    command:  Redis3-server --loglevel warning --requirepass debuggeandoideas
  
  
